### PR TITLE
Fix function comments based on best practices from Effective Go

### PR DESCRIPTION
**Pull request by CodeLingoTeam**
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?

### CODE REVIEW

**Comment by casualjim** [comment]
Interesting... did you do that with some tool?

**Comment by bcomnes** [comment]
I think its a bot.

**Comment by fredbi** [comment]
It is indeed, I've seen similar PRs in several golang repos.

**Comment by CodeLingoTeam** [comment]
@casualjim Yes, we did it with CLQL ([CodeLingo](https://www.codelingo.io/) Query Language). CLQL matches patterns in code and automates reviews, refactors, docs generation, etc. [This](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml#L296-L311) is the specific tenet that refactored your code.

@bcomnes @fredbi that's right, we've made several similar PRs on other Go repos, but there are humans behind @CodeLingoTeam! We review every PR manually, and will always respond if you @ us.

**Comment by fredbi** [comment]
We could probably run this CI again after recent changes with travis config. This PR is failing for no good reason.

**Pull request merged**
