### PR TITLE
feat: add pathParamEscaped support

### LINKED ISSUE #138: Provide raw path params support to runtime/client
Can you provide raw path params support to runtime/client so that the following paths for client request works.

```yaml
paths:
  '/repositories/{repo_name}/tags':
    get:
      summary: Get tags of a relevant repository.
      tags:
        - repository
      operationId: listRepositoryTags
      parameters:
        - name: repo_name
          in: path
          type: string
          required: true
          description: Relevant repository name.
      responses:
        '200':
          description: Get tags successfully.
          schema:
            type: array
            items:
              $ref: '#/definitions/DetailedTag'
```

```golang
params := repository.ListRepositoryTagsParams{
    RepoName: "library/ubuntu",
}

resp, err := h.Repository.ListRepositoryTags(ctx, &params)
```

current repo_name `library/ubuntu` will request to the API `/repositories/library%2Fubuntu/tags` but the expect API is `/repositories/library/ubuntu/tags`

### PR DESCRIPTION
**Pull request by alswl**
Provide a way to control path parmas.

fix https://github.com/go-openapi/runtime/issues/138

### CODE REVIEW

**Comment by youyuanwu** [comment]
https://github.com/go-openapi/runtime/issues/138 was marked as won't fix.
openapi v2 does not specify this behavior, so I vote down for this to be merged.
@casualjim thoughts?

**Comment by casualjim** [comment]
I think this is a risky change that allows for ambiguity in routes. 

It seems that it's not supported, unless I misunderstand the discussions here which is entirely possible:
https://github.com/OAI/OpenAPI-Specification/issues/892
https://github.com/OAI/OpenAPI-Specification/issues/2653

This is an open issue even for the current openapi specifications, so I'm also not in favor for this change.

**Comment by alswl** [comment]
Is it possible to proved a feature gate to enable this feature. In real world, some project is using `slash` in the HTTP router .

**Comment by youyuanwu** [comment]
If (when) openapi decides to incorporate this feature, go-openapi can add this support. But for now, please follow up with openapi feature proposals which casualjim linked above.

**Pull request closed without merging**
