### PR TITLE
add optional OpenTracing support for client

### PR DESCRIPTION
**Pull request by zeitlinger**
adds a wrapper for runtime.ClientTransport that adds OpenTracing support for all requests.

### CODE REVIEW

**Comment by fredbi** [comment]
:100:

**Comment by zeitlinger** [comment]
Is there a better way to get the peer hostname, e.g. from the request?

**Comment by fredbi** [comment]
> Is there a better way to get the peer hostname, e.g. from the request?

I assume this is the hostname of the caller. This is mostly okay like this. Could default to `os.Hostname()` is left empty.

**Comment by zeitlinger** [comment]
No, the remote hostname

**Comment by fredbi** [comment]
The remote hostname is stored by the client:
https://github.com/go-openapi/runtime/blob/d6bcd5b0000c496449f44c5d686169e1b3d003c1/client/runtime.go#L228

That being said, if I were some ops wiling to monitor traces emitted by the client, I'd rather have the host of the emitter (supposedly, I'll get another span from the server side with the same traceID).

**Comment by zeitlinger** [comment]
> That being said, if I were some ops wiling to monitor traces emitted by the client, I'd rather have the host of the emitter (supposedly, I'll get another span from the server side with the same traceID).

the host of the emitter is usually set as a default tag when initializing the tracer, which is vender dependent.

**Comment by fredbi** [comment]
> the host of the emitter is usually set as a default tag when initializing the tracer, which is vender dependent.
ok got it

**Comment by zeitlinger** [comment]
> The remote hostname is stored by the client:

I added method `WithOpenTracing` which picks up the host.
It returns `runtime.ClientTransport` instead of `*Runtime` - which works in my case. Could this be a drawback?

**Review by fredbi — APPROVED** [review]

**Comment by zeitlinger** [comment]
great - can you ping me when a new version is available?

**Comment by piepmatz** [comment]
@zeitlinger ping

**Comment by zeitlinger** [comment]
thanks a lot :smile:

**Pull request merged**
