### PR TITLE
different envs

### PR DESCRIPTION
**Pull request by minenok-tutu**
Current way of checking the debug flag may affect many current applications where DEBUG flag is specified more precisely. Let's avoid it.

### CODE REVIEW

**Comment by minenok-tutu** [comment]
@casualjim ?

**Comment by casualjim** [comment]
can you rebase ?
do you have an example of where this is a problem?

**Comment by minenok-tutu** [comment]
> do you have an example of where this is a problem?

We're using explicit version of the DEBUG env: true|false or 1|0. I think it is much more clearer this way. 

And another reason: if some developer accidentally would try to turn off the debug output via setting DEBUG to 0, it is not clear why nothing changed.

**Comment by minenok-tutu** [comment]
@casualjim ?

**Pull request merged**
